#!/usr/bin/env bash
# install nginx on your web-01
sudo apt-get update -y
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" >> /var/www/html/error404.html
sed -i '/server_name_/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sed -i '25i\ error_page 404 /error404.html;' /etc/nginx/sites-available/default
sudo service nginx restart
