#!/usr/bin/env bash
# install nginx on your web-01
sudo apt-get update
sudo apt-get install nginx -y
echo "Hello World!" | sudo tee  /var/www/html/index.html
st="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/nikikiarie permanent;"
sudo sed -i "s/server_name _;/$st/" /etc/ngnix/sites-enabled/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
st="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$st/" /etc/nginx/sites-enabled/default
sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default
sudo nginx -t
sudo service nginx restart
