#!/usr/bin/env bash
# fix server running nginx

sed -i "s/#user www-data/user ngnix/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
# kill apache if running
pkill apache2
#restart nginx
sudo -u nginx service nginx start
